services:
  memquran.api:
    image: memquran.api:latest
    container_name: memquran.api
    ports:
      - "3123:3123"
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://*:3123
    build:
      context: .
      dockerfile: MemQuran.Api/Dockerfile
