#  docker-compose -f .docker/docker-compose-memquran-api.yaml -p memquran up -d
#  docker-compose -f .docker/docker-compose-memquran-api.yaml -p memquran down

services:
  memquran.api:
    build:
      context: ../src
      dockerfile: MemQuran.Api/Dockerfile
    ports:
      - "3123:3123"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://*:3123;http://*:3122
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https/
